# Generated by Django 4.1.7 on 2023-03-06 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_techstack_updated_at_alter_techstack_tech_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techstack',
            name='url',
            field=models.URLField(),
        ),
    ]
